name: Nightly Test
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:
    
jobs:
  tests_schedule:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Ran from schedule"
  tests_manually:
    strategy:
      matrix:
        env: ${{ fromJSON('["prod", "dev"]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.event_name == 'workflow_dispatch' && 'hello from dispatch' || 'fallback' }}
          
